export const WORKOUTS = [
  {
    _id: 1,
    title: "Knebøy",
    category: "kne",
    description:
      "Lorem Ipsum is simply dummy text of the printing and typesetting industry. ",
    instructions: ["Vær sexy", "Vær ekstremt sexy", "Veldig bra"],
    videoes: ["", "", ""],
    images: ["", "", ""],
    equipmnent: ["", ""],
    set_information: "3 x 8-15 repitisjoner",
  },
  {
    _id: 2,
    title: "Utfall",
    category: "kne",
    description:
      "Lorem Ipsum is simply dummy text of the printing and typesetting industry. ",
    instructions: ["Vær sexy", "Vær ekstremt sexy", "Veldig bra"],
    videoes: ["", "", ""],
    images: ["", "", ""],
    equipmnent: ["", ""],
    set_information: "3 x 8-15 repitisjoner",
  },
  {
    _id: 3,
    title: "Benhev",
    category: "kne",
    description:
      "Lorem Ipsum is simply dummy text of the printing and typesetting industry. ",
    instructions: ["Vær sexy", "Vær ekstremt sexy", "Veldig bra"],
    videoes: ["", "", ""],
    images: ["", "", ""],
    equipmnent: ["", ""],
    set_information: "3 x 8-15 repitisjoner",
  },
  {
    _id: 4,
    title: "Hoftehev",
    category: "hofte",
    description:
      "Lorem Ipsum is simply dummy text of the printing and typesetting industry. ",
    instructions: ["Vær sexy", "Vær ekstremt sexy", "Veldig bra"],
    videoes: ["", "", ""],
    images: ["", "", ""],
    equipmnent: ["", ""],
    set_information: "3 x 8-15 repitisjoner",
  },
  {
    _id: 5,
    title: "Dans",
    category: "hofte",
    description:
      "Lorem Ipsum is simply dummy text of the printing and typesetting industry. ",
    instructions: ["Vær sexy", "Vær ekstremt sexy", "Veldig bra"],
    videoes: ["", "", ""],
    images: ["", "", ""],
    equipmnent: ["", ""],
    set_information: "3 x 8-15 repitisjoner",
  },

  {
    _id: 6,
    title: "Rygghev",
    category: "Rygg",
    description:
      "Lorem Ipsum is simply dummy text of the printing and typesetting industry. ",
    instructions: ["Vær sexy", "Vær ekstremt sexy", "Veldig bra"],
    videoes: ["", "", ""],
    images: ["", "", ""],
    equipmnent: ["", ""],
    set_information: "3 x 8-15 repitisjoner",
  },
  {
    _id: 7,
    title: "Skulderhev",
    category: "Skulder",
    description:
      "Lorem Ipsum is simply dummy text of the printing and typesetting industry. ",
    instructions: ["Vær sexy", "Vær ekstremt sexy", "Veldig bra"],
    videoes: ["", "", ""],
    images: ["", "", ""],
    equipmnent: ["", ""],
    set_information: "3 x 8-15 repitisjoner",
  },
];

export const WORKOUTSDAYPLAN = [
  {
    _id: 1,
    workoutplan: "cardio",
    title: "Knebøy",
    category: "kne",
    description:
      "Lorem Ipsum is simply dummy text of the printing and typesetting industry. ",
    instructions: ["Vær sexy", "Vær ekstremt sexy", "Veldig bra"],
    videoes: ["", "", ""],
    images: ["", "", ""],
    equipmnent: ["", ""],
    set_information: "3 x 8-15 repitisjoner",
    isCompleted: true,
  },
  {
    _id: 2,
    workoutplan: "cardio",
    title: "Utfall",
    category: "kne",
    description:
      "Lorem Ipsum is simply dummy text of the printing and typesetting industry. ",
    instructions: ["Vær sexy", "Vær ekstremt sexy", "Veldig bra"],
    videoes: ["", "", ""],
    images: ["", "", ""],
    equipmnent: ["", ""],
    set_information: "3 x 8-15 repitisjoner",
    isCompleted: true,
  },
  {
    _id: 3,
    workoutplan: "cardio",
    title: "Benhev",
    category: "kne",
    description:
      "Lorem Ipsum is simply dummy text of the printing and typesetting industry. ",
    instructions: ["Vær sexy", "Vær ekstremt sexy", "Veldig bra"],
    videoes: ["", "", ""],
    images: ["", "", ""],
    equipmnent: ["", ""],
    set_information: "3 x 8-15 repitisjoner",
    isCompleted: false,
  },
  {
    _id: 4,
    workoutplan: "cardio",
    title: "Hoftehev",
    category: "hofte",
    description:
      "Lorem Ipsum is simply dummy text of the printing and typesetting industry. ",
    instructions: ["Vær sexy", "Vær ekstremt sexy", "Veldig bra"],
    videoes: ["", "", ""],
    images: ["", "", ""],
    equipmnent: ["", ""],
    set_information: "3 x 8-15 repitisjoner",
    isCompleted: false,
  },
  {
    _id: 5,
    workoutplan: "cardio",
    title: "Dans",
    category: "hofte",
    description:
      "Lorem Ipsum is simply dummy text of the printing and typesetting industry. ",
    instructions: ["Vær sexy", "Vær ekstremt sexy", "Veldig bra"],
    videoes: ["", "", ""],
    images: ["", "", ""],
    equipmnent: ["", ""],
    set_information: "3 x 8-15 repitisjoner",
    isCompleted: false,
  },

  {
    _id: 6,
    workoutplan: "program",
    title: "Rygghev",
    category: "Rygg",
    description:
      "Lorem Ipsum is simply dummy text of the printing and typesetting industry. ",
    instructions: ["Vær sexy", "Vær ekstremt sexy", "Veldig bra"],
    videoes: ["", "", ""],
    images: ["", "", ""],
    equipmnent: ["", ""],
    set_information: "3 x 8-15 repitisjoner",
    isCompleted: true,
  },
  {
    _id: 7,
    workoutplan: "program",
    title: "Skulderhev",
    category: "Skulder",
    description:
      "Lorem Ipsum is simply dummy text of the printing and typesetting industry. ",
    instructions: ["Vær sexy", "Vær ekstremt sexy", "Veldig bra"],
    videoes: ["", "", ""],
    images: ["", "", ""],
    equipmnent: ["", ""],
    set_information: "3 x 8-15 repitisjoner",
    isCompleted: false,
  },
  {
    _id: 8,
    workoutplan: "program",
    title: "Skulderhev",
    category: "Skulder",
    description:
      "Lorem Ipsum is simply dummy text of the printing and typesetting industry. ",
    instructions: ["Vær sexy", "Vær ekstremt sexy", "Veldig bra"],
    videoes: ["", "", ""],
    images: ["", "", ""],
    equipmnent: ["", ""],
    set_information: "3 x 8-15 repitisjoner",
    isCompleted: false,
  },
  {
    _id: 9,
    workoutplan: "program",
    title: "Skulderhev",
    category: "Skulder",
    description:
      "Lorem Ipsum is simply dummy text of the printing and typesetting industry. ",
    instructions: ["Vær sexy", "Vær ekstremt sexy", "Veldig bra"],
    videoes: ["", "", ""],
    images: ["", "", ""],
    equipmnent: ["", ""],
    set_information: "3 x 8-15 repitisjoner",
    isCompleted: false,
  },
  {
    _id: 10,
    workoutplan: "program",
    title: "Skulderhev",
    category: "Skulder",
    description:
      "Lorem Ipsum is simply dummy text of the printing and typesetting industry. ",
    instructions: ["Vær sexy", "Vær ekstremt sexy", "Veldig bra"],
    videoes: ["", "", ""],
    images: ["", "", ""],
    equipmnent: ["", ""],
    set_information: "3 x 8-15 repitisjoner",
    isCompleted: false,
  },
  {
    _id: 11,
    workoutplan: "program",
    title: "Skulderhev",
    category: "Skulder",
    description:
      "Lorem Ipsum is simply dummy text of the printing and typesetting industry. ",
    instructions: ["Vær sexy", "Vær ekstremt sexy", "Veldig bra"],
    videoes: ["", "", ""],
    images: ["", "", ""],
    equipmnent: ["", ""],
    set_information: "3 x 8-15 repitisjoner",
    isCompleted: false,
  },
  {
    _id: 12,
    workoutplan: "cross fit",
    title: "Skulderhev",
    category: "Skulder",
    description:
      "Lorem Ipsum is simply dummy text of the printing and typesetting industry. ",
    instructions: ["Vær sexy", "Vær ekstremt sexy", "Veldig bra"],
    videoes: ["", "", ""],
    images: ["", "", ""],
    equipmnent: ["", ""],
    set_information: "3 x 8-15 repitisjoner",
    isCompleted: false,
  },
  {
    _id: 13,
    workoutplan: "cross fit",
    title: "Skulderhev",
    category: "Skulder",
    description:
      "Lorem Ipsum is simply dummy text of the printing and typesetting industry. ",
    instructions: ["Vær sexy", "Vær ekstremt sexy", "Veldig bra"],
    videoes: ["", "", ""],
    images: ["", "", ""],
    equipmnent: ["", ""],
    set_information: "3 x 8-15 repitisjoner",
    isCompleted: false,
  },
  {
    _id: 14,
    workoutplan: "cross fit",
    title: "Skulderhev",
    category: "Skulder",
    description:
      "Lorem Ipsum is simply dummy text of the printing and typesetting industry. ",
    instructions: ["Vær sexy", "Vær ekstremt sexy", "Veldig bra"],
    videoes: ["", "", ""],
    images: ["", "", ""],
    equipmnent: ["", ""],
    set_information: "3 x 8-15 repitisjoner",
    isCompleted: false,
  },
  {
    _id: 15,
    workoutplan: "cross fit",
    title: "Skulderhev",
    category: "Skulder",
    description:
      "Lorem Ipsum is simply dummy text of the printing and typesetting industry. ",
    instructions: ["Vær sexy", "Vær ekstremt sexy", "Veldig bra"],
    videoes: ["", "", ""],
    images: ["", "", ""],
    equipmnent: ["", ""],
    set_information: "3 x 8-15 repitisjoner",
    isCompleted: false,
  },
  {
    _id: 16,
    workoutplan: "cross fit",
    title: "Skulderhev",
    category: "Skulder",
    description:
      "Lorem Ipsum is simply dummy text of the printing and typesetting industry. ",
    instructions: ["Vær sexy", "Vær ekstremt sexy", "Veldig bra"],
    videoes: ["", "", ""],
    images: ["", "", ""],
    equipmnent: ["", ""],
    set_information: "3 x 8-15 repitisjoner",
    isCompleted: false,
  },
  {
    _id: 17,
    workoutplan: "cross fit",
    title: "Skulderhev",
    category: "Skulder",
    description:
      "Lorem Ipsum is simply dummy text of the printing and typesetting industry. ",
    instructions: ["Vær sexy", "Vær ekstremt sexy", "Veldig bra"],
    videoes: ["", "", ""],
    images: ["", "", ""],
    equipmnent: ["", ""],
    set_information: "3 x 8-15 repitisjoner",
    isCompleted: false,
  },
  {
    _id: 18,
    workoutplan: "arobics",
    title: "Skulderhev",
    category: "Skulder",
    description:
      "Lorem Ipsum is simply dummy text of the printing and typesetting industry. ",
    instructions: ["Vær sexy", "Vær ekstremt sexy", "Veldig bra"],
    videoes: ["", "", ""],
    images: ["", "", ""],
    equipmnent: ["", ""],
    set_information: "3 x 8-15 repitisjoner",
    isCompleted: true,
  },
  {
    _id: 19,
    workoutplan: "arobics",
    title: "Skulderhev",
    category: "Skulder",
    description:
      "Lorem Ipsum is simply dummy text of the printing and typesetting industry. ",
    instructions: ["Vær sexy", "Vær ekstremt sexy", "Veldig bra"],
    videoes: ["", "", ""],
    images: ["", "", ""],
    equipmnent: ["", ""],
    set_information: "3 x 8-15 repitisjoner",
    isCompleted: false,
  },
  {
    _id: 20,
    workoutplan: "arobics",
    title: "Skulderhev",
    category: "Skulder",
    description:
      "Lorem Ipsum is simply dummy text of the printing and typesetting industry. ",
    instructions: ["Vær sexy", "Vær ekstremt sexy", "Veldig bra"],
    videoes: ["", "", ""],
    images: ["", "", ""],
    equipmnent: ["", ""],
    set_information: "3 x 8-15 repitisjoner",
    isCompleted: true,
  },
  {
    _id: 21,
    workoutplan: "arobics",
    title: "Skulderhev",
    category: "Skulder",
    description:
      "Lorem Ipsum is simply dummy text of the printing and typesetting industry. ",
    instructions: ["Vær sexy", "Vær ekstremt sexy", "Veldig bra"],
    videoes: ["", "", ""],
    images: ["", "", ""],
    equipmnent: ["", ""],
    set_information: "3 x 8-15 repitisjoner",
    isCompleted: false,
  },
  {
    _id: 22,
    workoutplan: "arobics",
    title: "Skulderhev",
    category: "Skulder",
    description:
      "Lorem Ipsum is simply dummy text of the printing and typesetting industry. ",
    instructions: ["Vær sexy", "Vær ekstremt sexy", "Veldig bra"],
    videoes: ["", "", ""],
    images: ["", "", ""],
    equipmnent: ["", ""],
    set_information: "3 x 8-15 repitisjoner",
    isCompleted: false,
  },
  {
    _id: 23,
    workoutplan: "yoga",
    title: "Skulderhev",
    category: "Skulder",
    description:
      "Lorem Ipsum is simply dummy text of the printing and typesetting industry. ",
    instructions: ["Vær sexy", "Vær ekstremt sexy", "Veldig bra"],
    videoes: ["", "", ""],
    images: ["", "", ""],
    equipmnent: ["", ""],
    set_information: "3 x 8-15 repitisjoner",
    isCompleted: true,
  },
  {
    _id: 24,
    workoutplan: "yoga",
    title: "Skulderhev",
    category: "Skulder",
    description:
      "Lorem Ipsum is simply dummy text of the printing and typesetting industry. ",
    instructions: ["Vær sexy", "Vær ekstremt sexy", "Veldig bra"],
    videoes: ["", "", ""],
    images: ["", "", ""],
    equipmnent: ["", ""],
    set_information: "3 x 8-15 repitisjoner",
    isCompleted: true,
  },
  {
    _id: 25,
    workoutplan: "yoga",
    title: "Skulderhev",
    category: "Skulder",
    description:
      "Lorem Ipsum is simply dummy text of the printing and typesetting industry. ",
    instructions: ["Vær sexy", "Vær ekstremt sexy", "Veldig bra"],
    videoes: ["", "", ""],
    images: ["", "", ""],
    equipmnent: ["", ""],
    set_information: "3 x 8-15 repitisjoner",
    isCompleted: false,
  },
  {
    _id: 26,
    workoutplan: "yoga",
    title: "Skulderhev",
    category: "Skulder",
    description:
      "Lorem Ipsum is simply dummy text of the printing and typesetting industry. ",
    instructions: ["Vær sexy", "Vær ekstremt sexy", "Veldig bra"],
    videoes: ["", "", ""],
    images: ["", "", ""],
    equipmnent: ["", ""],
    set_information: "3 x 8-15 repitisjoner",
    isCompleted: false,
  },
  {
    _id: 27,
    workoutplan: "yoga",
    title: "Skulderhev",
    category: "Skulder",
    description:
      "Lorem Ipsum is simply dummy text of the printing and typesetting industry. ",
    instructions: ["Vær sexy", "Vær ekstremt sexy", "Veldig bra"],
    videoes: ["", "", ""],
    images: ["", "", ""],
    equipmnent: ["", ""],
    set_information: "3 x 8-15 repitisjoner",
    isCompleted: false,
  },
];

export const BODY_PARTS = [
  {
    _id: 1,
    title: "Ankel",
  },
  {
    _id: 2,
    title: "Kne",
  },
  {
    _id: 3,
    title: "Hofte",
  },
  {
    _id: 4,
    title: "Korsrygg",
  },
  {
    _id: 5,
    title: "Brystryggen",
  },
  {
    _id: 6,
    title: "Skulder",
  },
  {
    _id: 7,
    title: "Nakke",
  },
  {
    _id: 8,
    title: "Fot",
  },
  {
    _id: 9,
    title: "Albue",
  },
];

export const PROFILE_INFO = {
  _id: 1,
  diagnosis: "Artrose",
  diagnosis_info:
    "Lorem Ipsum is simply dummy text of the printing and typesetting industry.",
  message_from_terapaut:
    "Pasient burde intensitetsstyre belastning på vektbærende ledd ut ifra alvorlighetsgraden av symptomene.",
  plan: {
    _id: 1,
    img: "",
    description:
      "Lorem Ipsum is simply dummy text of the printing and typesetting industry. ",
  },
};

export const NOTIFICATION = [
  {
    _id: 1,
    message: "På tide å trene!",
    date: "10/10/2022",
  },
  {
    _id: 2,
    message: "På tide å trene!",
    date: "11/10/2022",
  },
  {
    _id: 3,
    message: "På tide å trene!",
    date: "12/10/2022",
  },
];

export const WORKOUTPLAN = [
  {
    _id: 1,
    title: "Cardio",
    color: ["#C4ECFF", "#89D9FF", "#00AEFF"],
    day: "Man",
    numberOfExercises: 5,
    duration: 45,
    isCompleted: true,
  },
  {
    _id: 2,
    title: "Program",
    color: ["#FFE6F2", "#FFC4E1", "#FF8CC4"],
    day: "Tir",
    numberOfExercises: 6,
    duration: 45,
    isCompleted: true,
  },
  {
    _id: 3,
    title: "Cross Fit",
    color: ["#D4AFFF", "#B779FF", "#9539FF"],
    day: "Ons",
    numberOfExercises: 6,
    duration: 45,
    isCompleted: true,
  },
  {
    _id: 4,
    title: "Arobics",
    color: ["#D6FFBA", "#A7D38A", "#63B928"],
    day: "Tor",
    numberOfExercises: 5,
    duration: 45,
    isCompleted: false,
  },
  {
    _id: 5,
    title: "Yoga",
    color: ["#D9D9FF", "#7876FF", "#0300FF"],
    day: "Fre",
    numberOfExercises: 5,
    duration: 45,
    isCompleted: false,
  },
];
